/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../sanity.schema.json
export type PageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'page';
};

export type ContactModule = {
  _type: 'contactModule';
  title: string;
  heading: string;
  actions: Array<{
    label: string;
    type: 'INTERNAL' | 'EXTERNAL';
    internalLink?: PageReference;
    externalUrl?: string;
    openInNewTab?: boolean;
    _type: 'link';
    _key: string;
  }>;
};

export type ToolingModule = {
  _type: 'toolingModule';
  title: string;
  tags: Tags;
};

export type ExperienceModule = {
  _type: 'experienceModule';
  title: string;
  experienceBlocks: Array<
    {
      _key: string;
    } & ExperienceBlock
  >;
};

export type TextModule = {
  _type: 'textModule';
  title: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type LinkReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'link';
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Hero = {
  _type: 'hero';
  headline: string;
  subheadline: string;
  callToActions: Array<
    | {
        platform: 'GITHUB' | 'LINKEDIN';
        link: LinkReference;
        name: string;
        _type: 'socialProfile';
        _key: string;
      }
    | {
        label: string;
        type: 'INTERNAL' | 'EXTERNAL';
        internalLink?: PageReference;
        externalUrl?: string;
        openInNewTab?: boolean;
        _type: 'link';
        _key: string;
      }
  >;
  eyebrow: Eyebrow;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type Eyebrow = string;

export type SeoBlock = {
  _type: 'seoBlock';
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  noIndex?: boolean;
};

export type ExperienceBlock = {
  _type: 'experienceBlock';
  company: string;
  role: string;
  startDate: string;
  endDate?: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SocialProfile = {
  _id: string;
  _type: 'socialProfile';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  platform: 'GITHUB' | 'LINKEDIN';
  link: LinkReference;
  name: string;
};

export type SocialProfileReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'socialProfile';
};

export type Footer = {
  _id: string;
  _type: 'footer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<
    | ({
        _key: string;
      } & LinkReference)
    | ({
        _key: string;
      } & SocialProfileReference)
  >;
  location?: string;
};

export type HeaderNavigation = {
  _id: string;
  _type: 'headerNavigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<
    {
      _key: string;
    } & LinkReference
  >;
};

export type Link = {
  _id: string;
  _type: 'link';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  type: 'INTERNAL' | 'EXTERNAL';
  internalLink?: PageReference;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type PageTemplateReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'pageTemplate';
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  identifier: string;
  slug: Slug;
  template: PageTemplateReference;
  seoBlock?: SeoBlock;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type PageTemplate = {
  _id: string;
  _type: 'pageTemplate';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  identifier: string;
  modules: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & TextModule)
    | ({
        _key: string;
      } & ExperienceModule)
    | ({
        _key: string;
      } & ToolingModule)
    | ({
        _key: string;
      } & ContactModule)
  >;
};

export type Tags = Array<
  {
    _key: string;
  } & Tag
>;

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Tag = {
  _type: 'tag';
  value?: string;
  label?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PageReference
  | ContactModule
  | ToolingModule
  | ExperienceModule
  | TextModule
  | LinkReference
  | SanityImageAssetReference
  | Hero
  | Eyebrow
  | SeoBlock
  | ExperienceBlock
  | SocialProfile
  | SocialProfileReference
  | Footer
  | HeaderNavigation
  | Link
  | PageTemplateReference
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | PageTemplate
  | Tags
  | Slug
  | Tag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/libs/sanity/queries/queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<never>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
