/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../sanity.schema.json
export type PageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'page';
};

export type ContactModule = {
  _type: 'contactModule';
  title: string;
  heading: string;
  actions: Array<{
    label: string;
    type: 'INTERNAL' | 'EXTERNAL';
    internalLink?: PageReference;
    externalUrl?: string;
    openInNewTab?: boolean;
    _type: 'link';
    _key: string;
  }>;
};

export type ToolingModule = {
  _type: 'toolingModule';
  title: string;
  tags: Tags;
};

export type ExperienceModule = {
  _type: 'experienceModule';
  title: string;
  experienceBlocks: Array<
    {
      _key: string;
    } & ExperienceBlock
  >;
};

export type TextModule = {
  _type: 'textModule';
  title: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type LinkReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'link';
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Hero = {
  _type: 'hero';
  headline: string;
  subheadline: string;
  callToActions: Array<
    | {
        platform: 'GITHUB' | 'LINKEDIN';
        link: LinkReference;
        name: string;
        _type: 'socialProfile';
        _key: string;
      }
    | {
        label: string;
        type: 'INTERNAL' | 'EXTERNAL';
        internalLink?: PageReference;
        externalUrl?: string;
        openInNewTab?: boolean;
        _type: 'link';
        _key: string;
      }
  >;
  eyebrow: Eyebrow;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type Eyebrow = string;

export type SeoBlock = {
  _type: 'seoBlock';
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  noIndex?: boolean;
};

export type ExperienceBlock = {
  _type: 'experienceBlock';
  company: string;
  role: string;
  startDate: string;
  endDate?: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SocialProfile = {
  _id: string;
  _type: 'socialProfile';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  platform: 'GITHUB' | 'LINKEDIN';
  link: LinkReference;
  name: string;
};

export type SocialProfileReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'socialProfile';
};

export type Footer = {
  _id: string;
  _type: 'footer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<
    | ({
        _key: string;
      } & LinkReference)
    | ({
        _key: string;
      } & SocialProfileReference)
  >;
  location?: string;
};

export type HeaderNavigation = {
  _id: string;
  _type: 'headerNavigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<
    {
      _key: string;
    } & LinkReference
  >;
};

export type Link = {
  _id: string;
  _type: 'link';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  type: 'INTERNAL' | 'EXTERNAL';
  internalLink?: PageReference;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type PageTemplateReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'pageTemplate';
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  identifier: string;
  slug: Slug;
  template: PageTemplateReference;
  seoBlock?: SeoBlock;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type PageTemplate = {
  _id: string;
  _type: 'pageTemplate';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  identifier: string;
  modules: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & TextModule)
    | ({
        _key: string;
      } & ExperienceModule)
    | ({
        _key: string;
      } & ToolingModule)
    | ({
        _key: string;
      } & ContactModule)
  >;
};

export type Tags = Array<
  {
    _key: string;
  } & Tag
>;

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Tag = {
  _type: 'tag';
  value?: string;
  label?: string;
};

export type MediaFolderReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'media.folder';
};

export type MediaFolder = {
  _id: string;
  _type: 'media.folder';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PageReference
  | ContactModule
  | ToolingModule
  | ExperienceModule
  | TextModule
  | LinkReference
  | SanityImageAssetReference
  | Hero
  | Eyebrow
  | SeoBlock
  | ExperienceBlock
  | SocialProfile
  | SocialProfileReference
  | Footer
  | HeaderNavigation
  | Link
  | PageTemplateReference
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | PageTemplate
  | Tags
  | Slug
  | Tag
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/libs/sanity/fragments/base.ts
// Variable: IMAGE_FRAGMENT
// Query: {    alt,    hotspot,    crop,    "asset": asset->{      _id,      url,      metadata {        lqip,        dimensions { width, height, aspectRatio }      }    }  }
export type IMAGE_FRAGMENT_RESULT = {
  alt: never;
  hotspot: never;
  crop: never;
  asset: never;
};

// Source: src/libs/sanity/fragments/base.ts
// Variable: LINK_FRAGMENT
// Query: {    label,    type,    "href": select(      type == 'INTERNAL' => internalLink->slug.current,      type == 'EXTERNAL' => externalUrl    ),    "openInNewTab": select(      type == 'EXTERNAL' => coalesce(openInNewTab, false),      false    )  }
export type LINK_FRAGMENT_RESULT = {
  label: never;
  type: never;
  href: null;
  openInNewTab: false;
};

// Source: src/libs/sanity/fragments/modules/hero.ts
// Variable: HERO_FRAGMENT
// Query: {    _key,    _type,    eyebrow,    headline,    subheadline,    image   {    alt,    hotspot,    crop,    "asset": asset->{      _id,      url,      metadata {        lqip,        dimensions { width, height, aspectRatio }      }    }  },    callToActions[]{      _key,      _type,      _type == 'link' =>   {    label,    type,    "href": select(      type == 'INTERNAL' => internalLink->slug.current,      type == 'EXTERNAL' => externalUrl    ),    "openInNewTab": select(      type == 'EXTERNAL' => coalesce(openInNewTab, false),      false    )  },      _type == 'socialProfile' => {        platform,        name,        link->  {    label,    type,    "href": select(      type == 'INTERNAL' => internalLink->slug.current,      type == 'EXTERNAL' => externalUrl    ),    "openInNewTab": select(      type == 'EXTERNAL' => coalesce(openInNewTab, false),      false    )  }      }    }  }
export type HERO_FRAGMENT_RESULT = {
  _key: never;
  _type: never;
  eyebrow: never;
  headline: never;
  subheadline: never;
  image: never;
  callToActions: never;
};

// Source: src/libs/sanity/queries/page.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    "modules": template->modules[]{      _key,      _type,      _type == "hero" =>   {    _key,    _type,    eyebrow,    headline,    subheadline,    image   {    alt,    hotspot,    crop,    "asset": asset->{      _id,      url,      metadata {        lqip,        dimensions { width, height, aspectRatio }      }    }  },    callToActions[]{      _key,      _type,      _type == 'link' =>   {    label,    type,    "href": select(      type == 'INTERNAL' => internalLink->slug.current,      type == 'EXTERNAL' => externalUrl    ),    "openInNewTab": select(      type == 'EXTERNAL' => coalesce(openInNewTab, false),      false    )  },      _type == 'socialProfile' => {        platform,        name,        link->  {    label,    type,    "href": select(      type == 'INTERNAL' => internalLink->slug.current,      type == 'EXTERNAL' => externalUrl    ),    "openInNewTab": select(      type == 'EXTERNAL' => coalesce(openInNewTab, false),      false    )  }      }    }  }    }  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: null;
  modules: Array<
    | {
        _key: string;
        _type: 'contactModule';
      }
    | {
        _key: string;
        _type: 'experienceModule';
      }
    | {
        _key: string;
        _type: 'hero';
        eyebrow: Eyebrow;
        headline: string;
        subheadline: string;
        image: {
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
        } | null;
        callToActions: Array<
          | {
              _key: string;
              _type: 'link';
              label: string;
              type: 'EXTERNAL' | 'INTERNAL';
              href: string | null;
              openInNewTab: boolean | false;
            }
          | {
              _key: string;
              _type: 'socialProfile';
              platform: 'GITHUB' | 'LINKEDIN';
              name: string;
              link: {
                label: string;
                type: 'EXTERNAL' | 'INTERNAL';
                href: string | null;
                openInNewTab: boolean | false;
              };
            }
        >;
      }
    | {
        _key: string;
        _type: 'textModule';
      }
    | {
        _key: string;
        _type: 'toolingModule';
      }
  >;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  {\n    alt,\n    hotspot,\n    crop,\n    "asset": asset->{\n      _id,\n      url,\n      metadata {\n        lqip,\n        dimensions { width, height, aspectRatio }\n      }\n    }\n  }\n': IMAGE_FRAGMENT_RESULT;
    "\n  {\n    label,\n    type,\n    \"href\": select(\n      type == 'INTERNAL' => internalLink->slug.current,\n      type == 'EXTERNAL' => externalUrl\n    ),\n    \"openInNewTab\": select(\n      type == 'EXTERNAL' => coalesce(openInNewTab, false),\n      false\n    )\n  }\n": LINK_FRAGMENT_RESULT;
    "\n  {\n    _key,\n    _type,\n    eyebrow,\n    headline,\n    subheadline,\n    image \n  {\n    alt,\n    hotspot,\n    crop,\n    \"asset\": asset->{\n      _id,\n      url,\n      metadata {\n        lqip,\n        dimensions { width, height, aspectRatio }\n      }\n    }\n  }\n,\n    callToActions[]{\n      _key,\n      _type,\n      _type == 'link' => \n  {\n    label,\n    type,\n    \"href\": select(\n      type == 'INTERNAL' => internalLink->slug.current,\n      type == 'EXTERNAL' => externalUrl\n    ),\n    \"openInNewTab\": select(\n      type == 'EXTERNAL' => coalesce(openInNewTab, false),\n      false\n    )\n  }\n,\n      _type == 'socialProfile' => {\n        platform,\n        name,\n        link->\n  {\n    label,\n    type,\n    \"href\": select(\n      type == 'INTERNAL' => internalLink->slug.current,\n      type == 'EXTERNAL' => externalUrl\n    ),\n    \"openInNewTab\": select(\n      type == 'EXTERNAL' => coalesce(openInNewTab, false),\n      false\n    )\n  }\n\n      }\n    }\n  }\n": HERO_FRAGMENT_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    "modules": template->modules[]{\n      _key,\n      _type,\n\n      _type == "hero" => \n  {\n    _key,\n    _type,\n    eyebrow,\n    headline,\n    subheadline,\n    image \n  {\n    alt,\n    hotspot,\n    crop,\n    "asset": asset->{\n      _id,\n      url,\n      metadata {\n        lqip,\n        dimensions { width, height, aspectRatio }\n      }\n    }\n  }\n,\n    callToActions[]{\n      _key,\n      _type,\n      _type == \'link\' => \n  {\n    label,\n    type,\n    "href": select(\n      type == \'INTERNAL\' => internalLink->slug.current,\n      type == \'EXTERNAL\' => externalUrl\n    ),\n    "openInNewTab": select(\n      type == \'EXTERNAL\' => coalesce(openInNewTab, false),\n      false\n    )\n  }\n,\n      _type == \'socialProfile\' => {\n        platform,\n        name,\n        link->\n  {\n    label,\n    type,\n    "href": select(\n      type == \'INTERNAL\' => internalLink->slug.current,\n      type == \'EXTERNAL\' => externalUrl\n    ),\n    "openInNewTab": select(\n      type == \'EXTERNAL\' => coalesce(openInNewTab, false),\n      false\n    )\n  }\n\n      }\n    }\n  }\n\n    }\n  }': PAGE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
